module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/config/routes.rb
Rails.application.routes.draw do
  resources :powers, only: [:index, :show]
  resources :heroines, only: [:index, :show, :new, :create]  
end

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/models/heroine.rb
class Heroine < ApplicationRecord
    has_many :powers, through: :heroine_powers

    validates :name, presence: true
    validates :super_name, presence: true, uniqueness: true

    def get_powers
        @powers = HeroinePowers.find(params[:id])
    end
end

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/models/heroine_power.rb
class HeroinePowers < ApplicationRecord
    has_many :powers
    has_many :heroines
end

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/models/power.rb
class Power < ApplicationRecord
    has_many :heroines, through: :heroine_powers
end

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/controllers/heroines_controller.rb
class HeroinesController < ApplicationController
  def index
    @heroines = Heroine.all
  end

  def show
    @heroine = Heroine.find(params[:id])
  end

  def new
    # @heroines = Heroine.all
    @heroine = Heroine.new
    # byebug
    @heroine.save
  end

  def create
    @heroine = Heroine.new(heroine_params)
    # byebug
  
    @heroine.save
  end


  private
  def heroine_params
    params.require(:heroine).permit(:name, :super_name)
  end
end

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/controllers/powers_controller.rb
class PowersController < ApplicationController
  def index
    @powers = Power.all
  end

  def show
    @power = Power.find(params[:id])
  end
end

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/views/heroines/index.html.erb
<h2>All Heroines</h2>

<ul>
  <% @heroines.each do |heroine| %>
    <li>
      <%= link_to heroine.super_name, heroine_path(heroine) %>
    </li>
    <br>
  <% end %>
</ul>

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/views/heroines/new.html.erb
<%= form_for @heroine do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :super_name %>
    <%= f.text_field :super_name %><br>
    <%= f.label :power %>
    <%= form_for :power do |g| %>
        <%= g.collection_select(:power_id, Power.all, :id, :name) %>
    <% end %><br>
    <%= f.submit %>
<% end %>


<% if @heroine.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@heroine.errors.count, "error") %> prohibited this heroine from being saved:</h2>
 
    <ul>
    <% @heroine.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/views/heroines/show.html.erb
<h1>Super Name: <%=@heroine.super_name%></h1>
<p>Real Name: <%=@heroine.name%></p>

<%# <p>Powers: <%=@heroine.get_powers.each do |power| %>
    <%# <p>link_to power.name, power_path(power)</p> %>
    <%# <%end%>

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/views/powers/index.html.erb
<h2>All Superpowers</h2>

<ul>
  <% @powers.each do |power| %>
    <li>
      <%= link_to power.name, power_path(power) %>
      <br>
      Description: <%= power.description %>
    </li>
    <br>
  <% end %>
</ul>

module-2-code-challenge-round-1-seattle-web-12091-module-2-code-challenge---superheroines-1579295117/app/views/powers/show.html.erb
<h1>Power Name: <%=@power.name%></h1>
<p>Description: <%=@power.description%></p>